# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-17 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laureates', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laurete',
            new_name='Laureate',
        ),
    ]
