# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-17 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='motivation',
            field=models.CharField(max_length=256),
        ),
    ]
