# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-17 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laureates', '0002_auto_20171117_2302'),
        ('prizes', '0002_auto_20171117_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizeaward',
            name='laureate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laureates.Laureate'),
        ),
        migrations.AddField(
            model_name='prizeaward',
            name='motivation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='prize',
            name='motivation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
